source 'https://rubygems.org'
gem 'ecdsa' #Used to generate and verify signatures.
gem 'rack-rpc' #Runs the KademliaNode inside a Rack stack, and exposes its RPC functionality.

gem 'digest-sha3' #For the default Digest class, which is Keccak.

gem 'rspec', :require => 'spec' #For running tests